### ISSUE TITLE
gradle run succesfully and who run project where is resoure and how to use this library

### ISSUE THREAD

**Issue by mallikarjuna009** [zalando/tokens#130]

**Comment by whiskeysierra** [comment]
I'd argue that the README covers everything. What's missing from your perspective?

**Comment by mallikarjuna009** [comment]
how can use this . how to run in eclipse . where it helpfull

**Comment by whiskeysierra** [comment]
> how can use this

Add the dependency to your project and configure it as described in the README.

> how to run in eclipse

It's an ordinary Maven project, you should be able to just import it.It's uesful for microservices that are running in a [STUPS](https://stups.io/) environment and need OAuth2 access tokens to call other services.
