### ISSUE TITLE
here which uri i have to add. my resouse one or another

### ISSUE THREAD

**Issue by mallikarjuna009** [zalando/tokens#133]
AccessTokens tokens = Tokens.createAccessTokensWithUri(new URI("https://this.url.will.be.ignored"))
                            .start();

here which uri i have to add. my resouse one or another

token not creating when 

Exception in thread "main" java.lang.IllegalArgumentException: No tokens configured
	at org.zalando.stups.tokens.AccessTokensBuilder.getAccessTokenRefresher(AccessTokensBuilder.java:583)
	at org.zalando.stups.tokens.AccessTokensBuilder.start(AccessTokensBuilder.java:565)
showing exception

**Comment by whiskeysierra** [comment]
> here which uri i have to add. my resouse one or another

The URL of the service that can grant you access tokens.

> Exception in thread "main" java.lang.IllegalArgumentException: No tokens configured

See usage at https://github.com/zalando/tokens#usage-in-zalandos-stups-environment.

**Comment by mallikarjuna009** [comment]
please provide your mail id

**Comment by whiskeysierra** [comment]
Discussions on issues should be public so other's can benefit from it.
