### ISSUE TITLE
Measure time for request tokeninfo.

### ISSUE THREAD

**Issue by jbellmann** [zalando/tokens#34]

**Comment by jbellmann** [comment]
Where to show results? Standard-Out, File,Listener? Any ideas?

**Comment by Jan-M** [comment]
Yes. This should be in the metrics endpoint. Basically use the existing
metrics registry in the spring project.

On Tuesday, 16 February 2016, Jörg Bellmann <notifications@github.com>
wrote:

> Where to show results? Standard-Out, File,Listener? Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zalando-stups/tokens/issues/34#issuecomment-184718054>
> .
>


-- 
Jan Mußler
Senior Database Engineer | +49 176 1275 8727 | Zalando SE

**Comment by LappleApple** [comment]
Hi @jbellmann @duergner @harti2006: Can we close this issue from Feb 2016? Or can we label "Help Wanted"?

**Comment by jbellmann** [comment]
[It's already implemented.](https://github.com/zalando/tokens/blob/master/src/main/java/org/zalando/stups/tokens/CloseableTokenVerifier.java#L106)

Users just have to register an 'EventListener/Callback' during configuration. Unknown feature. Nobody uses it afaik.

Closing this issue would be ok from my side.

Regards
Jörg

**Comment by LappleApple** [comment]
Thanks, @jbellmann.
