### ISSUE TITLE
Consider Env-Variable 'OAUTH2_ACCESS_TOKEN_URL'

### ISSUE THREAD

**Issue by jbellmann** [zalando/tokens#45]

**Comment by lmineiro** [comment]
I like the idea but would prefer to have a consistent naming pattern with the token info counter part which, currently, is `TOKENINFO_URL`.

**Comment by hjacobs** [comment]
Relevant change in Taupage: https://github.com/zalando-stups/taupage/issues/186

**Comment by LappleApple** [comment]
Hey @jbellmann @duergner @harti2006 @lmineiro @hjacobs, anything to do here? Can we close it?

**Comment by jbellmann** [comment]
I think this was resolved with #76.
