### ISSUE TITLE
AccessTokenConfiguration.addScope should be more strongly typed

### ISSUE THREAD

**Issue by jhorstmann** [zalando/tokens#56]
Currently it's taking an `Object` as a parameter, which means it's easy to accidentally use this method instead of `addScopes`, without causing compiler errors. See https://github.com/zalando/tokens/blob/master/src/main/java/org/zalando/stups/tokens/AccessTokenConfiguration.java#L56

This leads to error messages like the following, where you have to look really hard to see the misplaced semicolon.

```
{
    "error":"invalid_scope",
    "error_description":"Unknown/invalid scope(s): [some_service.read], [uid,]"
}
```

**Comment by jbellmann** [comment]
@jhorstmann Where is the semicolon. Can't see any :-)

But do have any ideas how to fix this? Adding some validation?

**Comment by jhorstmann** [comment]
I probably meant the comma instead of semicolon :)

Is there a reason that the scopes are typed as `Object`? I would expect them to be Strings. Changing this would be an incompatible change though, so maybe a first step would be adding a `addScope(final String scope)` method and marking ´addScope(final Object scope)` as deprecated, so you'd at least get a warning in your IDE.

**Comment by mastersimon** [comment]
+1 for @jhorstmann .
I was asking me the same question today: Why is addScope[s]() consuming an Object? Does it make sense?
Addition to this, if you insert an empty String (which is an object) it runs into a similar problem as Joern posted (`"error_description":"Unknown/invalid scope(s): [some_service.read], [uid,]"`) but without content. It´s easy to check if the value is null or empty if we switch it from `Object` to `String`.

**Comment by harti2006** [comment]
@sarnowski I remember there was a use case for the `Object`parameter. Can you please shed a light on this?

Anyway, I think overloading the method with a String argument is a good idea.

**Comment by LappleApple** [comment]
@jhorstmann @mastersimon Hey, do you require additional help here? If not, we'll close.

**Comment by mastersimon** [comment]
Why do you ask if we require additional information? I guess the need/improvement is quite clear. Is it already solved?

**Comment by LappleApple** [comment]
@mastersimon My question says "help," not "information." If you still need the change, then you can let the maintainers know.

**Comment by mastersimon** [comment]
Well, it is an improvement. I need no help since I already know the problem. However, I'm sure it keeps others from running into the same problem.
It´s up to the maintainers if they implement it.

**Comment by LappleApple** [comment]
Or you could make a PR. @jbellmann, @harti2006, @duergner, WDYT?

**Comment by duergner** [comment]
If we implement it I'd fully go with the suggestion from @jhorstmann.

I myself don't really a use case for the scope being an object. If a client requires the scope to be an object it should be solvable by calling `toString()` explicitly outside of the library. So unless @sarnowski has some real hard facts why it's not a good idea I'd vote for that change.
