### ISSUE TITLE
How to get started

### ISSUE THREAD

**Issue by akauppi** [zalando/tokens#59]
I expected the `README` to have basic, no Java background needed, instructions on how to e.g. run tests on the project, and otherwise get started. Could such be added?

I tried:

```
$ mvn test
...
Tests run: 56, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 48.992 s
[INFO] Finished at: 2016-11-05T23:49:52+02:00
[INFO] Final Memory: 24M/306M
[INFO] ------------------------------------------------------------------------
```

While that eventually provides the above message, it does show multiple call stacks during the execution, which made me think the code did not run well on my clone. 

Is this normal in Java?

I'd like:
- `mvn test` to be mentioned in the README
- to see no stack traces when tests pass

Thanks for considering.

**Comment by duergner** [comment]
It's not absolutely unusual for tests to print stack traces even in case they pass.

Regarding the `mvn test` part on the README, could you consider opening up a PR with what you consider would make sense?

**Comment by LappleApple** [comment]
Hi, checking in on this to see what the next step might be. We could probably get one of any number of Zalando's using this project to help with these very essential onboarding details. Sound good?

**Comment by duergner** [comment]
Sounds definitely like a plan.

@akauppi I'm not 100% sure which type of getting started you would like to have: Getting started as a user or getting started as a developer?

**Comment by LappleApple** [comment]
+10 to both @duergner @akauppi, we can split these so no single person has to do it all
