### ISSUE TITLE
java.lang.NoClassDefFoundError: Fatal execution error, caused by org/apache/http/util/Args

### ISSUE THREAD

**Issue by Unisay** [zalando/tokens#60]
First of all, thank you, guys, for the very well written library!

I am trying to use it from Scala and upon the very first run I get this error:
```
java.lang.NoClassDefFoundError: Fatal execution error, caused by org/apache/http/util/Args
java.lang.NoClassDefFoundError: org/apache/http/util/Args
	at org.zalando.stups.tokens.util.Objects.notNull(Objects.java:37)
        ....
```

It comes down to the lack of: 
```
"org.apache.httpcomponents" % "httpcore" % "4.4"
```
which I can obviously solve by declaring it as a dependency in the `build.sbt`,
but I wonder why isn't it included transitively with 

```
"org.zalando.stups" % "tokens" % "0.9.9-gh52-1"
```

**Comment by hjacobs** [comment]
Isn't this related to #44?

**Comment by Unisay** [comment]
Yes, it is. Having provided scope documented solves the problem

**Comment by jbellmann** [comment]
For the latest [release](https://github.com/zalando/tokens/releases/tag/0.10.0) we decided to change the scope to 'compile' so that 'httpclient' will be resolved as transitive dependency to avoid confusing users.

Please try out the latest release and report any issue you have with it.
