### ISSUE TITLE
Make the refresher thread a daemon thread

### ISSUE THREAD

**Issue by dcherepovsky** [zalando/tokens#65]
This library's threads should not prevent JVM from being terminated, if they are the only threads still alive.

**Comment by hjacobs** [comment]
FYI: I haven't seen problems with this library and JVM not terminating.

**Comment by dcherepovsky** [comment]
@hjacobs I have a pretty simple single-threaded Scala app right now, which uses this lib. Main thread just finishes. JVM is not terminated.
I don't think it's Scala-specific.
