### ISSUE TITLE
Consider switching 'httpclient' dependency

### ISSUE THREAD

**Issue by jbellmann** [zalando/tokens#69]
... to be a compile/runtime dependency.

To avoid issues like #60 .

Another point would be to maybe force the user to have latest to be up to date. To hopefully avoid issues like #52 .

**Comment by jbellmann** [comment]
@harti2006 ??

**Comment by harti2006** [comment]
but what about https://github.com/zalando/tokens/pull/14 ?
This PR /feature would be completely obsolete then.

**Comment by jbellmann** [comment]
No, not true, imo. The #14 brings in all the abstractions needed to drop the default-implementation (provided by us) and plug in a different one (maybe async, as mentioned in #14). That's fine.

Here we talk about 'shipping' the dependency (library) needed by our 'default-implementation'. Users are still able to completely put in their own 'HttpProvider' implementation (maybe with 'httpclient-async' or 'ok-http').
But we could improve the 'out-of-the-box' experience for 'tokens' with default-implementation working without putting the user in responsibility to care about adding dependencies we already know about.
Excluding this library from users project should be simple for an developer.

**Comment by harti2006** [comment]
Ok, I agree. So if someone does not want to use our implementation, they can simply exclude Apache httpclient from their dependencies configuration 👍 
Then it makes sense to add it as compile time dependency.

**Comment by jbellmann** [comment]
Nice, will create the PR for this and let you know.

**Comment by jbellmann** [comment]
Fixed with [0.10.0](https://github.com/zalando/tokens/releases/tag/0.10.0)
