### ISSUE TITLE
Would be nice to have a CHANGELOG

### ISSUE THREAD

**Issue by akauppi** [zalando/tokens#77]
Where to see what's changed since, say, 0.9.9-gh52-1

I was expecting the GitHub "release" page to have details. It doesn't. And there's no `CHANGELOG` file, either. Where should I look?

**Comment by hjacobs** [comment]
In general the tokens lib needs some love regarding documentation (also for the new Kubernetes support)..

**Comment by jbellmann** [comment]
👍

**Comment by LappleApple** [comment]
Hey @hjacobs + @akauppi, can you list some "desired doc fixes," thinking about how externals might be able to support that work? A top three bullet points would be great and low-maintenance.

**Comment by whiskeysierra** [comment]
I'll just leave this here as a reference: http://keepachangelog.com/en/0.3.0/

**Comment by hjacobs** [comment]
My personal wish would be to simply use the GitHub releases feature as a changelog: https://github.com/zalando/tokens/releases

Some examples:

* https://github.com/zalando/connexion/releases
* https://github.com/zalando-incubator/kube-ingress-aws-controller/releases

**Comment by vadeg** [comment]
@akauppi is this ticket is still relevant/

**Comment by vadeg** [comment]
Github releases contains this information since 2019. Feel free to reopen this ticket if needed.
