### ISSUE TITLE
Concurrency issue at Closed

### ISSUE THREAD

**Issue by gagoman** [zalando/tokens#81]
Hello.

[here](https://github.com/zalando/tokens/blob/2eff93887dd88975d0ecb19faf18a95cbfb6e6da/src/main/java/org/zalando/stups/tokens/mcb/Closed.java#L52) `get` followed by `decrementAndGet` is not an atomic operation which
can and will lead to `-1` in a lot of cases.

It's up to maintainers to decide if this is critical enough to be fixed.

[jcstress](https://wiki.openjdk.java.net/display/CodeTools/jcstress) test:

```java
import org.openjdk.jcstress.annotations.Actor;
import org.openjdk.jcstress.annotations.Arbiter;
import org.openjdk.jcstress.annotations.Expect;
import org.openjdk.jcstress.annotations.JCStressTest;
import org.openjdk.jcstress.annotations.Outcome;
import org.openjdk.jcstress.annotations.State;
import org.openjdk.jcstress.infra.results.IntResult1;

import java.util.concurrent.atomic.AtomicInteger;

@JCStressTest
@Outcome(id = "0", expect = Expect.ACCEPTABLE, desc = "Expected one.")
@Outcome(id = "-1", expect = Expect.FORBIDDEN, desc = "Actual one.")
@State
public class TokensAtomicDecrementIssue {
    AtomicInteger errorCount = new AtomicInteger(1);

    @Actor
    public void actor1() {
        if (errorCount.get() > 0) {
            errorCount.decrementAndGet();
        }
    }

    @Actor
    public void actor2() {
        if (errorCount.get() > 0) {
            errorCount.decrementAndGet();
        }
    }

    @Arbiter
    public void arbiter(IntResult1 r) {
        r.r1 = errorCount.get();
    }
}
```

```
[FAILED] org.sample.TokensAtomicDecrementIssue
    (JVM args: [-server])
  Observed state   Occurrences   Expectation  Interpretation
              -1     8,613,209     FORBIDDEN  Actual one.
               0    30,942,501    ACCEPTABLE  Expected one.
```

**Comment by jbellmann** [comment]
Thanks a lot for reporting the issue.
I'm not aware of 'jcstress' but I will invest some time to find out what it is good for.

I'm now guessing, so correct me if I'm wrong. 'jcstress' runs multiple Threads against 'actor1()' and 'actor2()' and at some point we came to the point that one thread passes the condition with 'true' and context-switch kicks in before doing the 'decrementAndGet' while another thread also passes the condition with 'true' does the 'decrementAndGet' and during the next context-switch the first thread will also do a 'decrementAndGet'. Does this describe the scenario in your stress-test?

But I think we don't have this scenario in our case. MCBs (Minimal-Circuit-Breaker) used here are accessed/invoked by only one thread created/controlled by the scheduler. And from the documentation of 'ScheduledExecutorService' 

> ... If any execution of this task takes longer than its period, then subsequent executions may start late, but will not concurrently execute.

So in my opinion this is not really a critical issue here. I see two possible solutions here:

- just make it an 'synchronized' method to avoid any concurrency-issues
- reset the 'errorCount' to '0' without any condition before (what is already mentioned in the TODO comment)

What do you think?

**Comment by gagoman** [comment]
> I'm now guessing, so correct me if I'm wrong. 'jcstress' runs multiple Threads against 'actor1()' and 'actor2()' and at some point in time we came to the point that one thread passes the condition with 'true' and context-switch kicks in before doing the 'decrementAndGet' while another thread also passes the condition with 'true' does the 'decrementAndGet' and during the next context-switch the first thread will also do a 'decrementAndGet'. Does this describe the scenario in your stress-test?

* Yes, your assumptions are valid.
* Yes, that could lead to "off by one" error with MCB. In bad case it will require one extra `onError` to reach valid state.

> But I think we don't have this scenario in our case. MCBs (Minimal-Circuit-Breaker) used here are accessed/invoked by only one thread created/controlled by the scheduler. And from the documentation of 'ScheduledExecutorService'

Thats really cool.

> What do you think?

According to `pom.xml` the target version is `1.8`, so we can use `updateAndGet` or `getAndUpdate` to fix an issue.

```java
@JCStressTest
@Outcome(id = "0", expect = Expect.ACCEPTABLE, desc = "Valid result.")
@Outcome(id = "-1", expect = Expect.FORBIDDEN, desc = "Bad result.")
@State
public class TokensAtomicDecrementIssue {
    AtomicInteger errorCount = new AtomicInteger(1);

    @Actor
    public void actor1() {
        errorCount.updateAndGet(count -> count > 0 ? count - 1 : 0);
    }

    @Actor
    public void actor2() {
        errorCount.updateAndGet(count -> count > 0 ? count - 1 : 0);
    }

    @Arbiter
    public void arbiter(IntResult1 r) {
        r.r1 = errorCount.get();
    }
}
```

**Comment by jbellmann** [comment]
@gagoman 
thanks for making me aware of 'jcstress' and providing a solution with 'LongUnaryOperator' ;-)
So much new stuff to learn in Java 8.

Regards
