### ISSUE TITLE
Dependency to commons-logging

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/tokens#90]
Do we need it? Can we exclude it from `httpclient`?

**Comment by hjacobs** [comment]
@lukasniemeier-zalando I have no idea, but I guess you have better expertise to decide :smile:

**Comment by lukasniemeier-zalando** [comment]
I am assigning the issue to @whiskeysierra as I'm arguing with him about it :wink:

**Comment by whiskeysierra** [comment]
![Are you serious?](http://vignette1.wikia.nocookie.net/theamazingworldofgumball/images/9/93/Are_you_serious.png/revision/latest?cb=20120820000819)

**Comment by lukasniemeier-zalando** [comment]
I am proposing to do the following in the tokens `pom.xml`:

```
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>x.x.x</version>
    <exclusions>
        <exclusion>
            <artifactId>commons-logging</artifactId>
            <groupId>commons-logging</groupId>
        </exclusion>
    </exclusions>
</dependency>
```

Then users of tokens need to either have `commons-logging` or something else (e.g. jcl-slf4j bridge `jcl-over-slf4j`) on the classpath. This way we allow higher flexibility for the users while not polluting the classpath. See also [here](https://stackoverflow.com/questions/3222895/what-is-the-issue-with-the-runtime-discovery-algorithm-of-apache-commons-logging/3223701#3223701).
