### ISSUE TITLE
token-configuration

### ISSUE THREAD

**Issue by skokorin** [zalando/tokens#98]
I'm trying to use tokens library on kubi...

Somehow it fails on first try with error:
no token

and somehow ok on further requests.

I've added
.getFilesystemSecretsRefresherConfiguration.validateTokensOnStartup()
to a builder and now I'm receiving an error:
The following token-configurations couldn't be found : [default-token]

**Comment by jbellmann** [comment]
@skokorin If you still have trouble using the library or you still experience this issue please ping me via company chat, to discuss in more detail and maybe see some logs.
